language: php

php:
  - 5.4

before_script:
  - sh -c "mysql -e 'CREATE DATABASE fateca;'"
  - sh -c "mysql -e 'CREATE DATABASE fateca_test;'"
  - mkdir ./app/tmp
  - chmod -R 777 ./app/tmp
  - chmod 777 ./app/Console/cake*
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'datasource' => 'Database/Mysql',
      'database' => 'fateca',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
    );
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'fateca_test',
      'host' => '0.0.0.0',
      'login' => 'travis'
      'persistent' => false,
    );
    }" > ./app/Config/database.php
 
script:
  - sh -c "./app/Console/cake test app AllTests --stderr"

notifications:
email: false